apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "webrtc-cctv-frontend.fullname" . }}-selfsigned-crt
spec:
  secretName: {{ include "webrtc-cctv-frontend.fullname" . }}-tls-secret
  duration: 170000h
  renewBefore: 72h
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  commonName: "web.{{ .Release.Namespace }}.svc.cluster.local"
  isCA: true
  dnsNames:
  - "web.{{ .Release.Namespace }}.svc.cluster.local"
  - "*.{{ .Release.Namespace }}.svc.cluster.local"